[package]
name = "shim-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
zksync_da_clients = { path = "../zksync-era/core/node/da_clients" }
zksync_config = { path = "../zksync-era/core/lib/config" }